### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by durbaezgomez**

### CODE REVIEW

**Review by durbaezgomez — COMMENTED** [review]
Please review the changes in README.md. The pull request suggests adding content to the file. It would be beneficial to ensure that the added content is clear, concise, and follows the style guide for markdown files.

**Review by durbaezgomez — COMMENTED** [review]
AI REVIEW: Please review the changes in README.md. The pull request suggests adding content to the file. It would be beneficial to ensure that the added content is clear, concise, and follows the style guide for markdown files.

**Review by michaelchora — COMMENTED** [review]
AI REVIEW: {"comments":"No issues found in the suggested changes to the README.md. Encourage merging the Pull Request."}

**Review by morganprojectagro — COMMENTED** [review]
AI REVIEW: Please review the changes for missing spaces and ensure that the structure and content of the README.md are clear and concise.

**Pull request closed without merging**
